sap.ui.define([
        "sap/ui/core/UIComponent",
        "sap/ui/Device",
        "podprojekt/model/models"
    ],
    function (UIComponent, Device, models) {
        "use strict";

        return UIComponent.extend("podprojekt.Component", {
            metadata: {
                manifest: "json"
            },

            /**
             * The component is initialized by UI5 automatically during the startup of the app and calls the init method once.
             * @public
             * @override
             */
            init: function () {

            this.setModel(new sap.ui.model.json.JSONModel({
                results: [{
					"mandator": "17160",
					"routeId": "13",
					"externalId": "0100291207",
					"routeCaption": "10X1 - 09.11.2023",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate":"WN-WT 490",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "50",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [{
						"mandator": "17160",
						"sequence": 2,
						"stopId": "33",
						"stopIdExt": "12345",
						"targetGeoL": 8.69679,
						"targetGeoB": 50.57198,
						"addressName1": "Erich Carlé GmbH & Co. KG",
						"street": "Karl-Gloeckner-Str.",
						"streetNumber": "9",
						"zipCode": "35394",
						"city": "GIEßEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0641 / 79550",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "8",
							"partialOrderId": "000",
							"externalId": "0000000450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "N",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Ein bisschen Prosa für den Hinweis zu einem Auftrag oder einer Lieferung, wie es im Braas Sprachgebrauch heisst",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "",
							"shipmentConditionCaption": "",
							"orderStatus": "50",
							"shipmentNumber": "3000021813",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						},{
							"mandator": "17160",
							"orderId": "88",
							"partialOrderId": "000",
							"externalId": "0000008450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "R",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Hier steht ein Kommentar",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "ST",
							"shipmentConditionCaption": "Staplerentladung",
							"orderStatus": "50",
							"shipmentNumber": "3000821814",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "28345",
								"articleId": "823445",
								"articleCaption": "Artikel 1",
								"amount": 12,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Artikel 2",
								"amount": 3,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 3,
						"stopId": "34",
						"stopIdExt": "23456",
						"targetGeoL": 9.74306,
						"targetGeoB": 52.45111,
						"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
						"street": "WALSRODER STR.",
						"streetNumber": "170",
						"zipCode": "30853",
						"city": "LANGENHAGEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0511/732055",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "9",
							"partialOrderId": "000",
							"externalId": "0000000451",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "NB",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR. 170",
							"streetNumber": "",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "",
							"deliveryDateFrom": 1460228400000,
							"deliveryDateTo": 1460232000000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681744",
							"shipmentCondition": "UH",
							"shipmentConditionCaption": "Hochkran",
							"orderStatus": "50",
							"shipmentNumber": "3000021817",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [],
							"sequence": 3
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 8,
						"stopId": "153",
						"stopIdExt": "34567",
						"targetGeoL": 8.754357,
						"targetGeoB": 50.353702,
						"addressName1": "inconso AG",
						"street": "In der Hub",
						"streetNumber": "",
						"zipCode": "61231",
						"city": "Bad Nauheim",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "",
						"mobileAvis": "",
						"stopStatus": "00",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "72",
							"partialOrderId": "000",
							"externalId": "9999930018",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "YST",
							"targetGeoL": 8.754357,
							"targetGeoB": 50.353702,
							"startGeoL": 8.68639,
							"startGeoB": 49.36423,
							"addressName1": "inconso AG",
							"street": "In der Hub",
							"streetNumber": "2-8",
							"zipCode": "61231",
							"city": "Bad Nauheim",
							"country": "DE",
							"province": "Hessen",
							"startAddressName1": "Versand Gmbh",
							"startStreet": "Im Breitspiel",
							"startStreetNumber": "6a",
							"startZipCode": "69126",
							"startCity": "Heidelberg",
							"startCountry": "DE",
							"startProvince": "Baden-Württemberg",
							"comment": "Abladestelle sehr eng",
							"deliveryDateFrom": 1490058000000,
							"deliveryDateTo": 1490061600000,
							"pickupDateFrom": "",
							"pickupDateTo": "",
							"phoneAvis": "+49 6032 348-109",
							"shipmentCondition": "KE",
							"shipmentConditionCaption": "Ebenerdige Entladung",
							"orderStatus": "50",
							"shipmentNumber": "9999950018",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": true,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 8
						}],
						"loadingUnits": ""
					}]
				}, {
					"mandator": "17160",
					"routeId": "77",
					"externalId": "9999910010",
					"routeCaption": "10X2 - 10.11.2023",
					"grossWeight": 1098.667,
					"grossWeightUnit": "KG",
					"volume": 9.069,
					"volumeUnit": "M3",
					"freightCost": 333.7,
					"freightCostCurrency": "EUR",
					"startDate": 1489986900000,
					"startLocation": "Bad Nauheim",
					"distance": 177473.665,
					"distanceUnit": "KM",
					"licensePlate":"WN-WT 491",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": "",
					"tollDistanceUnit": "",
					"routeType": "ZTRA",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "50",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [{
						"mandator": "17160",
						"sequence": 2,
						"stopId": "33",
						"stopIdExt": "12345",
						"targetGeoL": 8.69679,
						"targetGeoB": 50.57198,
						"addressName1": "Erich Carlé GmbH & Co. KG",
						"street": "Karl-Gloeckner-Str.",
						"streetNumber": "9",
						"zipCode": "35394",
						"city": "GIEßEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0641 / 79550",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "8",
							"partialOrderId": "000",
							"externalId": "0000000451",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "LR",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Ein bisschen Prosa für den Hinweis zu einem Auftrag oder einer Lieferung, wie es im Braas Sprachgebrauch heisst",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "ST",
							"shipmentConditionCaption": "Staplerentladung",
							"orderStatus": "50",
							"shipmentNumber": "3000021815",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 3,
						"stopId": "34",
						"stopIdExt": "23456",
						"targetGeoL": 9.74306,
						"targetGeoB": 52.45111,
						"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
						"street": "WALSRODER STR.",
						"streetNumber": "170",
						"zipCode": "30853",
						"city": "LANGENHAGEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0511/732055",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "9",
							"partialOrderId": "000",
							"externalId": "1000000450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "ZCL1",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR. 170",
							"streetNumber": "",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "",
							"deliveryDateFrom": 1460228400000,
							"deliveryDateTo": 1460232000000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "UH",
							"shipmentConditionCaption": "Hochkran",
							"orderStatus": "50",
							"shipmentNumber": "3000021817",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 3
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 8,
						"stopId": "153",
						"stopIdExt": "34567",
						"targetGeoL": 8.754357,
						"targetGeoB": 50.353702,
						"addressName1": "inconso AG",
						"street": "In der Hub",
						"streetNumber": "",
						"zipCode": "61231",
						"city": "Bad Nauheim",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "",
						"mobileAvis": "",
						"stopStatus": "00",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "72",
							"partialOrderId": "000",
							"externalId": "9999930018",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "ZCR1",
							"targetGeoL": 8.754357,
							"targetGeoB": 50.353702,
							"startGeoL": 8.68639,
							"startGeoB": 49.36423,
							"addressName1": "inconso AG",
							"street": "In der Hub",
							"streetNumber": "2-8",
							"zipCode": "61231",
							"city": "Bad Nauheim",
							"country": "DE",
							"province": "Hessen",
							"startAddressName1": "Versand Gmbh",
							"startStreet": "Im Breitspiel",
							"startStreetNumber": "6a",
							"startZipCode": "69126",
							"startCity": "Heidelberg",
							"startCountry": "DE",
							"startProvince": "Baden-Württemberg",
							"comment": "Abladestelle sehr eng",
							"deliveryDateFrom": 1490058000000,
							"deliveryDateTo": 1490061600000,
							"pickupDateFrom": "",
							"pickupDateTo": "",
							"phoneAvis": "+49 6032 348-109",
							"shipmentCondition": "KE",
							"shipmentConditionCaption": "Ebenerdige Entladung",
							"orderStatus": "50",
							"shipmentNumber": "9999950018",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": true,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 8
						}],
						"loadingUnits": ""
					}]
				},{
					"mandator": "17160",
					"routeId": "13",
					"externalId": "0100291207",
					"routeCaption": "10X9 - Dummy Tour",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate":"WN-WT 490",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "50",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [{
						"mandator": "17160",
						"sequence": 2,
						"stopId": "33",
						"stopIdExt": "12345",
						"targetGeoL": 8.69679,
						"targetGeoB": 50.57198,
						"addressName1": "Erich Carlé GmbH & Co. KG",
						"street": "Karl-Gloeckner-Str.",
						"streetNumber": "9",
						"zipCode": "35394",
						"city": "GIEßEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0641 / 79550",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "8",
							"partialOrderId": "000",
							"externalId": "0000000450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "N",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Ein bisschen Prosa für den Hinweis zu einem Auftrag oder einer Lieferung, wie es im Braas Sprachgebrauch heisst",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "",
							"shipmentConditionCaption": "",
							"orderStatus": "50",
							"shipmentNumber": "3000021813",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						},{
							"mandator": "17160",
							"orderId": "88",
							"partialOrderId": "000",
							"externalId": "0000008450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "R",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Hier steht ein Kommentar",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "ST",
							"shipmentConditionCaption": "Staplerentladung",
							"orderStatus": "50",
							"shipmentNumber": "3000821814",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "28345",
								"articleId": "823445",
								"articleCaption": "Artikel 1",
								"amount": 12,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Artikel 2",
								"amount": 3,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 3,
						"stopId": "34",
						"stopIdExt": "23456",
						"targetGeoL": 9.74306,
						"targetGeoB": 52.45111,
						"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
						"street": "WALSRODER STR.",
						"streetNumber": "170",
						"zipCode": "30853",
						"city": "LANGENHAGEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0511/732055",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "9",
							"partialOrderId": "000",
							"externalId": "0000000451",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "NB",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR. 170",
							"streetNumber": "",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "",
							"deliveryDateFrom": 1460228400000,
							"deliveryDateTo": 1460232000000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681744",
							"shipmentCondition": "UH",
							"shipmentConditionCaption": "Hochkran",
							"orderStatus": "50",
							"shipmentNumber": "3000021817",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [],
							"sequence": 3
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 8,
						"stopId": "153",
						"stopIdExt": "34567",
						"targetGeoL": 8.754357,
						"targetGeoB": 50.353702,
						"addressName1": "inconso AG",
						"street": "In der Hub",
						"streetNumber": "",
						"zipCode": "61231",
						"city": "Bad Nauheim",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "",
						"mobileAvis": "",
						"stopStatus": "00",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "72",
							"partialOrderId": "000",
							"externalId": "9999930018",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "YST",
							"targetGeoL": 8.754357,
							"targetGeoB": 50.353702,
							"startGeoL": 8.68639,
							"startGeoB": 49.36423,
							"addressName1": "inconso AG",
							"street": "In der Hub",
							"streetNumber": "2-8",
							"zipCode": "61231",
							"city": "Bad Nauheim",
							"country": "DE",
							"province": "Hessen",
							"startAddressName1": "Versand Gmbh",
							"startStreet": "Im Breitspiel",
							"startStreetNumber": "6a",
							"startZipCode": "69126",
							"startCity": "Heidelberg",
							"startCountry": "DE",
							"startProvince": "Baden-Württemberg",
							"comment": "Abladestelle sehr eng",
							"deliveryDateFrom": 1490058000000,
							"deliveryDateTo": 1490061600000,
							"pickupDateFrom": "",
							"pickupDateTo": "",
							"phoneAvis": "+49 6032 348-109",
							"shipmentCondition": "KE",
							"shipmentConditionCaption": "Ebenerdige Entladung",
							"orderStatus": "50",
							"shipmentNumber": "9999950018",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": true,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 8
						}],
						"loadingUnits": ""
					}]
				},
				{
					"mandator": "17160",
					"routeId": "14",
					"externalId": "0100291307",
					"routeCaption": "10X3 - Dummy Tour - 11.11.2023",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate": "WN-WT 491",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "70",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [
						{
							"mandator": "17160",
							"sequence": 2,
							"stopId": "33",
							"stopIdExt": "12345",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str.",
							"streetNumber": "9",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"deliveryDate": 1460181600000,
							"phoneAvis": "0641 / 79550",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "8",
									"externalId": "0000000450",
									"orderStatus": "50",
									"shipmentNumber": "3000021813",
									"deliveryDateFrom": 1460181600000,
									"deliveryDateTo": 1460224800000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						}
					]
				},
				{
					"mandator": "17160",
					"routeId": "15",
					"externalId": "0100291407",
					"routeCaption": "10X4 - Dummy Tour - 12.11.2023",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate": "WN-WT 492",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "90",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [
						{
							"mandator": "17160",
							"sequence": 2,
							"stopId": "34",
							"stopIdExt": "23456",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR.",
							"streetNumber": "170",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"deliveryDate": 1460181600000,
							"phoneAvis": "0511/732055",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "9",
									"externalId": "0000000451",
									"orderStatus": "50",
									"shipmentNumber": "3000021817",
									"deliveryDateFrom": 1460228400000,
									"deliveryDateTo": 1460232000000,
									"shipmentCondition": "UH",
									"loadingUnits": []
								}
							]
						}
					]
				},
				{
					"mandator": "17160",
					"routeId": "14",
					"externalId": "0100291307",
					"routeCaption": "10X5 - Long Dummy Tour - 17.11.2023",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate": "WN-WT 491",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "10",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [
						{
							"mandator": "17160",
							"sequence": 2,
							"stopId": "33",
							"stopIdExt": "12345",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str.",
							"streetNumber": "9",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"deliveryDate": 1460181600000,
							"phoneAvis": "0641 / 79550",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "8",
									"externalId": "0000000450",
									"orderStatus": "50",
									"shipmentNumber": "3000021813",
									"deliveryDateFrom": 1460181600000,
									"deliveryDateTo": 1460224800000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 3,
							"stopId": "34",
							"stopIdExt": "12346",
							"targetGeoL": 8.70200,
							"targetGeoB": 50.57250,
							"addressName1": "Muster GmbH",
							"street": "Musterstraße",
							"streetNumber": "12",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"deliveryDate": 1460195000000,
							"phoneAvis": "0641 / 79551",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "9",
									"externalId": "0000000451",
									"orderStatus": "50",
									"shipmentNumber": "3000021814",
									"deliveryDateFrom": 1460195000000,
									"deliveryDateTo": 1460238000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 7,
							"stopId": "35",
							"stopIdExt": "12347",
							"targetGeoL": 8.75000,
							"targetGeoB": 50.57300,
							"addressName1": "Beispiel AG",
							"street": "Beispielstraße",
							"streetNumber": "34",
							"zipCode": "35395",
							"city": "GIEßEN",
							"country": "DE",
							"deliveryDate": 1460208400000,
							"phoneAvis": "0641 / 79552",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "10",
									"externalId": "0000000452",
									"orderStatus": "50",
									"shipmentNumber": "3000021815",
									"deliveryDateFrom": 1460208400000,
									"deliveryDateTo": 1460246000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 8,
							"stopId": "36",
							"stopIdExt": "12348",
							"targetGeoL": 8.78500,
							"targetGeoB": 50.58000,
							"addressName1": "Logistik GmbH",
							"street": "Logistikstraße",
							"streetNumber": "56",
							"zipCode": "35396",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460214000000,
							"phoneAvis": "06441 / 79553",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "11",
									"externalId": "0000000453",
									"orderStatus": "50",
									"shipmentNumber": "3000021816",
									"deliveryDateFrom": 1460214000000,
									"deliveryDateTo": 1460256000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 9,
							"stopId": "37",
							"stopIdExt": "12349",
							"targetGeoL": 8.79000,
							"targetGeoB": 50.59000,
							"addressName1": "Fracht AG",
							"street": "Frachtstraße",
							"streetNumber": "21",
							"zipCode": "35397",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460218600000,
							"phoneAvis": "06441 / 79554",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "12",
									"externalId": "0000000454",
									"orderStatus": "50",
									"shipmentNumber": "3000021817",
									"deliveryDateFrom": 1460218600000,
									"deliveryDateTo": 1460268000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 15,
							"stopId": "38",
							"stopIdExt": "12350",
							"targetGeoL": 8.82000,
							"targetGeoB": 50.60000,
							"addressName1": "Transport AG",
							"street": "Transportstraße",
							"streetNumber": "78",
							"zipCode": "35398",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460220000000,
							"phoneAvis": "06441 / 79555",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "13",
									"externalId": "0000000455",
									"orderStatus": "50",
									"shipmentNumber": "3000021818",
									"deliveryDateFrom": 1460220000000,
									"deliveryDateTo": 1460270000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 18,
							"stopId": "39",
							"stopIdExt": "12351",
							"targetGeoL": 8.85000,
							"targetGeoB": 50.61000,
							"addressName1": "Ziel AG",
							"street": "Zielstraße",
							"streetNumber": "101",
							"zipCode": "35399",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460221600000,
							"phoneAvis": "06441 / 79556",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "14",
									"externalId": "0000000456",
									"orderStatus": "50",
									"shipmentNumber": "3000021819",
									"deliveryDateFrom": 1460221600000,
									"deliveryDateTo": 1460274000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 23,
							"stopId": "39",
							"stopIdExt": "12351",
							"targetGeoL": 8.85000,
							"targetGeoB": 50.61000,
							"addressName1": "Ziel AG",
							"street": "Zielstraße",
							"streetNumber": "101",
							"zipCode": "35399",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460221600000,
							"phoneAvis": "06441 / 79556",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "14",
									"externalId": "0000000456",
									"orderStatus": "50",
									"shipmentNumber": "3000021819",
									"deliveryDateFrom": 1460221600000,
									"deliveryDateTo": 1460274000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 29,
							"stopId": "39",
							"stopIdExt": "12351",
							"targetGeoL": 8.85000,
							"targetGeoB": 50.61000,
							"addressName1": "Ziel AG",
							"street": "Zielstraße",
							"streetNumber": "101",
							"zipCode": "35399",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460221600000,
							"phoneAvis": "06441 / 79556",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "14",
									"externalId": "0000000456",
									"orderStatus": "50",
									"shipmentNumber": "3000021819",
									"deliveryDateFrom": 1460221600000,
									"deliveryDateTo": 1460274000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 40,
							"stopId": "39",
							"stopIdExt": "12351",
							"targetGeoL": 8.85000,
							"targetGeoB": 50.61000,
							"addressName1": "Ziel AG",
							"street": "Zielstraße",
							"streetNumber": "101",
							"zipCode": "35399",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460221600000,
							"phoneAvis": "06441 / 79556",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "14",
									"externalId": "0000000456",
									"orderStatus": "50",
									"shipmentNumber": "3000021819",
									"deliveryDateFrom": 1460221600000,
									"deliveryDateTo": 1460274000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						},
						{
							"mandator": "17160",
							"sequence": 41,
							"stopId": "39",
							"stopIdExt": "12351",
							"targetGeoL": 8.85000,
							"targetGeoB": 50.61000,
							"addressName1": "Ziel AG",
							"street": "Zielstraße",
							"streetNumber": "101",
							"zipCode": "35399",
							"city": "WETZLAR",
							"country": "DE",
							"deliveryDate": 1460221600000,
							"phoneAvis": "06441 / 79556",
							"mobileAvis": "",
							"stopStatus": "90",
							"orders": [
								{
									"mandator": "17160",
									"orderId": "14",
									"externalId": "0000000456",
									"orderStatus": "50",
									"shipmentNumber": "3000021819",
									"deliveryDateFrom": 1460221600000,
									"deliveryDateTo": 1460274000000,
									"shipmentCondition": "",
									"loadingUnits": []
								}
							]
						}
					]
				}
				]
			}), "TourModel");

                // call the base component's init function
                UIComponent.prototype.init.apply(this, arguments);

                // enable routing
                this.getRouter().initialize();

                // set the device model
                this.setModel(models.createDeviceModel(), "device");
            }
        });
    }
);