/**
 * eslint-disable @sap/ui5-jsdocs/no-jsdoc
 */

sap.ui.define([
        "sap/ui/core/UIComponent",
        "sap/ui/Device",
        "podprojekt/model/models"
    ],
    function (UIComponent, Device, models) {
        "use strict";

        return UIComponent.extend("podprojekt.Component", {
            metadata: {
                manifest: "json"
            },

            /**
             * The component is initialized by UI5 automatically during the startup of the app and calls the init method once.
             * @public
             * @override
             */
            init: function () {

            this.setModel(new sap.ui.model.json.JSONModel({
                results: [{
					"mandator": "17160",
					"routeId": "13",
					"externalId": "0100291207",
					"routeCaption": "10X1 - 09.11.2023",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate":"WN-WT 490",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "90",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [{
						"mandator": "17160",
						"sequence": 2,
						"stopId": "33",
						"stopIdExt": "12345",
						"targetGeoL": 8.69679,
						"targetGeoB": 50.57198,
						"addressName1": "Erich Carlé GmbH & Co. KG",
						"street": "Karl-Gloeckner-Str.",
						"streetNumber": "9",
						"zipCode": "35394",
						"city": "GIEßEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0641 / 79550",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "8",
							"partialOrderId": "000",
							"externalId": "0000000450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "N",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Ein bisschen Prosa für den Hinweis zu einem Auftrag oder einer Lieferung, wie es im Braas Sprachgebrauch heisst",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "",
							"shipmentConditionCaption": "",
							"orderStatus": "50",
							"shipmentNumber": "3000021813",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						},{
							"mandator": "17160",
							"orderId": "88",
							"partialOrderId": "000",
							"externalId": "0000008450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "R",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Hier steht ein Kommentar",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "ST",
							"shipmentConditionCaption": "Staplerentladung",
							"orderStatus": "50",
							"shipmentNumber": "3000821814",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "28345",
								"articleId": "823445",
								"articleCaption": "Artikel 1",
								"amount": 12,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Artikel 2",
								"amount": 3,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 3,
						"stopId": "34",
						"stopIdExt": "23456",
						"targetGeoL": 9.74306,
						"targetGeoB": 52.45111,
						"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
						"street": "WALSRODER STR.",
						"streetNumber": "170",
						"zipCode": "30853",
						"city": "LANGENHAGEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0511/732055",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "9",
							"partialOrderId": "000",
							"externalId": "0000000451",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "NB",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR. 170",
							"streetNumber": "",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "",
							"deliveryDateFrom": 1460228400000,
							"deliveryDateTo": 1460232000000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681744",
							"shipmentCondition": "UH",
							"shipmentConditionCaption": "Hochkran",
							"orderStatus": "50",
							"shipmentNumber": "3000021817",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [],
							"sequence": 3
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 8,
						"stopId": "153",
						"stopIdExt": "34567",
						"targetGeoL": 8.754357,
						"targetGeoB": 50.353702,
						"addressName1": "inconso AG",
						"street": "In der Hub",
						"streetNumber": "",
						"zipCode": "61231",
						"city": "Bad Nauheim",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "",
						"mobileAvis": "",
						"stopStatus": "00",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "72",
							"partialOrderId": "000",
							"externalId": "9999930018",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "YST",
							"targetGeoL": 8.754357,
							"targetGeoB": 50.353702,
							"startGeoL": 8.68639,
							"startGeoB": 49.36423,
							"addressName1": "inconso AG",
							"street": "In der Hub",
							"streetNumber": "2-8",
							"zipCode": "61231",
							"city": "Bad Nauheim",
							"country": "DE",
							"province": "Hessen",
							"startAddressName1": "Versand Gmbh",
							"startStreet": "Im Breitspiel",
							"startStreetNumber": "6a",
							"startZipCode": "69126",
							"startCity": "Heidelberg",
							"startCountry": "DE",
							"startProvince": "Baden-Württemberg",
							"comment": "Abladestelle sehr eng",
							"deliveryDateFrom": 1490058000000,
							"deliveryDateTo": 1490061600000,
							"pickupDateFrom": "",
							"pickupDateTo": "",
							"phoneAvis": "+49 6032 348-109",
							"shipmentCondition": "KE",
							"shipmentConditionCaption": "Ebenerdige Entladung",
							"orderStatus": "50",
							"shipmentNumber": "9999950018",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": true,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 8
						}],
						"loadingUnits": ""
					}]
				}, {
					"mandator": "17160",
					"routeId": "77",
					"externalId": "9999910010",
					"routeCaption": "10X2 - 10.11.2023",
					"grossWeight": 1098.667,
					"grossWeightUnit": "KG",
					"volume": 9.069,
					"volumeUnit": "M3",
					"freightCost": 333.7,
					"freightCostCurrency": "EUR",
					"startDate": 1489986900000,
					"startLocation": "Bad Nauheim",
					"distance": 177473.665,
					"distanceUnit": "KM",
					"licensePlate":"WN-WT 491",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": "",
					"tollDistanceUnit": "",
					"routeType": "ZTRA",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "50",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [{
						"mandator": "17160",
						"sequence": 2,
						"stopId": "33",
						"stopIdExt": "12345",
						"targetGeoL": 8.69679,
						"targetGeoB": 50.57198,
						"addressName1": "Erich Carlé GmbH & Co. KG",
						"street": "Karl-Gloeckner-Str.",
						"streetNumber": "9",
						"zipCode": "35394",
						"city": "GIEßEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0641 / 79550",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "8",
							"partialOrderId": "000",
							"externalId": "0000000451",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "LR",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Ein bisschen Prosa für den Hinweis zu einem Auftrag oder einer Lieferung, wie es im Braas Sprachgebrauch heisst",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "ST",
							"shipmentConditionCaption": "Staplerentladung",
							"orderStatus": "50",
							"shipmentNumber": "3000021815",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 3,
						"stopId": "34",
						"stopIdExt": "23456",
						"targetGeoL": 9.74306,
						"targetGeoB": 52.45111,
						"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
						"street": "WALSRODER STR.",
						"streetNumber": "170",
						"zipCode": "30853",
						"city": "LANGENHAGEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0511/732055",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "9",
							"partialOrderId": "000",
							"externalId": "1000000450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "ZCL1",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR. 170",
							"streetNumber": "",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "",
							"deliveryDateFrom": 1460228400000,
							"deliveryDateTo": 1460232000000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "UH",
							"shipmentConditionCaption": "Hochkran",
							"orderStatus": "50",
							"shipmentNumber": "3000021817",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 3
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 8,
						"stopId": "153",
						"stopIdExt": "34567",
						"targetGeoL": 8.754357,
						"targetGeoB": 50.353702,
						"addressName1": "inconso AG",
						"street": "In der Hub",
						"streetNumber": "",
						"zipCode": "61231",
						"city": "Bad Nauheim",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "",
						"mobileAvis": "",
						"stopStatus": "00",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "72",
							"partialOrderId": "000",
							"externalId": "9999930018",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "ZCR1",
							"targetGeoL": 8.754357,
							"targetGeoB": 50.353702,
							"startGeoL": 8.68639,
							"startGeoB": 49.36423,
							"addressName1": "inconso AG",
							"street": "In der Hub",
							"streetNumber": "2-8",
							"zipCode": "61231",
							"city": "Bad Nauheim",
							"country": "DE",
							"province": "Hessen",
							"startAddressName1": "Versand Gmbh",
							"startStreet": "Im Breitspiel",
							"startStreetNumber": "6a",
							"startZipCode": "69126",
							"startCity": "Heidelberg",
							"startCountry": "DE",
							"startProvince": "Baden-Württemberg",
							"comment": "Abladestelle sehr eng",
							"deliveryDateFrom": 1490058000000,
							"deliveryDateTo": 1490061600000,
							"pickupDateFrom": "",
							"pickupDateTo": "",
							"phoneAvis": "+49 6032 348-109",
							"shipmentCondition": "KE",
							"shipmentConditionCaption": "Ebenerdige Entladung",
							"orderStatus": "50",
							"shipmentNumber": "9999950018",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": true,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 8
						}],
						"loadingUnits": ""
					}]
				},{
					"mandator": "17160",
					"routeId": "13",
					"externalId": "0100291207",
					"routeCaption": "10X9 - Dummy Tour",
					"grossWeight": 357.6,
					"grossWeightUnit": "KG",
					"volume": "",
					"volumeUnit": "M3",
					"freightCost": "",
					"freightCostCurrency": "",
					"startDate": 1460113760000,
					"startLocation": "Heusenstamm",
					"distance": 387.661,
					"distanceUnit": "KM",
					"licensePlate":"WN-WT 490",
					"mileage": 380000,
					"mileageTolerance": 600,
					"tollDistance": 371.0,
					"tollDistanceUnit": "KM",
					"routeType": "",
					"routeTypeCaption": "",
					"returnRoute": false,
					"routeStatus": "70",
					"deliveryAgreement": "",
					"deliveryAgreementBarcode": "",
					"stops": [{
						"mandator": "17160",
						"sequence": 2,
						"stopId": "33",
						"stopIdExt": "12345",
						"targetGeoL": 8.69679,
						"targetGeoB": 50.57198,
						"addressName1": "Erich Carlé GmbH & Co. KG",
						"street": "Karl-Gloeckner-Str.",
						"streetNumber": "9",
						"zipCode": "35394",
						"city": "GIEßEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0641 / 79550",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "8",
							"partialOrderId": "000",
							"externalId": "0000000450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "N",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Ein bisschen Prosa für den Hinweis zu einem Auftrag oder einer Lieferung, wie es im Braas Sprachgebrauch heisst",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "",
							"shipmentConditionCaption": "",
							"orderStatus": "50",
							"shipmentNumber": "3000021813",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						},{
							"mandator": "17160",
							"orderId": "88",
							"partialOrderId": "000",
							"externalId": "0000008450",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "R",
							"targetGeoL": 8.69679,
							"targetGeoB": 50.57198,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "Erich Carlé GmbH & Co. KG",
							"street": "Karl-Gloeckner-Str. 9",
							"streetNumber": "",
							"zipCode": "35394",
							"city": "GIEßEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "Hier steht ein Kommentar",
							"deliveryDateFrom": 1460181600000,
							"deliveryDateTo": 1460224800000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681742",
							"shipmentCondition": "ST",
							"shipmentConditionCaption": "Staplerentladung",
							"orderStatus": "50",
							"shipmentNumber": "3000821814",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "28345",
								"articleId": "823445",
								"articleCaption": "Artikel 1",
								"amount": 12,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "88",
								"partialOrderId": "000",
								"externalId": "9999988011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Artikel 2",
								"amount": 3,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 2
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 3,
						"stopId": "34",
						"stopIdExt": "23456",
						"targetGeoL": 9.74306,
						"targetGeoB": 52.45111,
						"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
						"street": "WALSRODER STR.",
						"streetNumber": "170",
						"zipCode": "30853",
						"city": "LANGENHAGEN",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "0511/732055",
						"mobileAvis": "",
						"stopStatus": "90",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "9",
							"partialOrderId": "000",
							"externalId": "0000000451",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "NB",
							"targetGeoL": 9.74306,
							"targetGeoB": 52.45111,
							"startGeoL": 8.81864,
							"startGeoB": 50.0573,
							"addressName1": "WILHELM ALTHANS GMBH U. CO.KG",
							"street": "WALSRODER STR. 170",
							"streetNumber": "",
							"zipCode": "30853",
							"city": "LANGENHAGEN",
							"country": "DE",
							"province": "",
							"startAddressName1": "Heusenstamm",
							"startStreet": "Rembrücker Straße 50",
							"startStreetNumber": "",
							"startZipCode": "63150",
							"startCity": "Heusenstamm",
							"startCountry": "DE",
							"startProvince": "",
							"comment": "",
							"deliveryDateFrom": 1460228400000,
							"deliveryDateTo": 1460232000000,
							"pickupDateFrom": 1460073600000,
							"pickupDateTo": "",
							"phoneAvis": "01739681744",
							"shipmentCondition": "UH",
							"shipmentConditionCaption": "Hochkran",
							"orderStatus": "50",
							"shipmentNumber": "3000021817",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": false,
							"loadingUnits": [],
							"sequence": 3
						}],
						"loadingUnits": ""
					}, {
						"mandator": "17160",
						"sequence": 8,
						"stopId": "153",
						"stopIdExt": "34567",
						"targetGeoL": 8.754357,
						"targetGeoB": 50.353702,
						"addressName1": "inconso AG",
						"street": "In der Hub",
						"streetNumber": "",
						"zipCode": "61231",
						"city": "Bad Nauheim",
						"country": "DE",
						"deliveryDate": 1460181600000,
						"phoneAvis": "",
						"mobileAvis": "",
						"stopStatus": "00",
						"stationDateFrom": "",
						"stationDateTo": "",
						"loadingDevicesAccountInfo": [],
						"orders": [{
							"mandator": "17160",
							"orderId": "72",
							"partialOrderId": "000",
							"externalId": "9999930018",
							"partialExternalId": "000",
							"orderNumber": "",
							"principalNumber": "",
							"kind": "YST",
							"targetGeoL": 8.754357,
							"targetGeoB": 50.353702,
							"startGeoL": 8.68639,
							"startGeoB": 49.36423,
							"addressName1": "inconso AG",
							"street": "In der Hub",
							"streetNumber": "2-8",
							"zipCode": "61231",
							"city": "Bad Nauheim",
							"country": "DE",
							"province": "Hessen",
							"startAddressName1": "Versand Gmbh",
							"startStreet": "Im Breitspiel",
							"startStreetNumber": "6a",
							"startZipCode": "69126",
							"startCity": "Heidelberg",
							"startCountry": "DE",
							"startProvince": "Baden-Württemberg",
							"comment": "Abladestelle sehr eng",
							"deliveryDateFrom": 1490058000000,
							"deliveryDateTo": 1490061600000,
							"pickupDateFrom": "",
							"pickupDateTo": "",
							"phoneAvis": "+49 6032 348-109",
							"shipmentCondition": "KE",
							"shipmentConditionCaption": "Ebenerdige Entladung",
							"orderStatus": "50",
							"shipmentNumber": "9999950018",
							"estimatedTimeOfArrival": "",
							"orderStatusText": "",
							"positionConfirm": true,
							"loadingUnits": [{
								"mandator": "17160",
								"loadingUnitId": "10",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980010",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22345",
								"articleId": "123445",
								"articleCaption": "Testartikel",
								"amount": 25,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "11",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980011",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22342",
								"articleId": "145322",
								"articleCaption": "Testprodukt",
								"amount": 5,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}, {
								"mandator": "17160",
								"loadingUnitId": "12",
								"orderId": "72",
								"partialOrderId": "000",
								"externalId": "9999980012",
								"length": "",
								"width": "",
								"height": "",
								"volume": "",
								"weight": "",
								"storingUnits": "",
								"loadingUnitStatus": "00",
								"loadingUnitStatusText": "",
								"isReturning": false,
								"netWeight": "",
								"taraWeight": "",
								"assortmentId": "",
								"loadingDeviceTypeId": "",
								"loadingDeviceId": "",
								"lodingDeviceTypeCaption": "Euro-Palette",
								"label1": "22231",
								"articleId": "233456",
								"articleCaption": "Testartikel",
								"amount": 100,
								"quantityUnit": "ST",
								"deliveryNotePositionNo": "",
								"sortingNo": ""
							}],
							"sequence": 8
						}],
						"loadingUnits": ""
					}]
				}]
			}), "TourModel");

			this.setModel(new sap.ui.model.json.JSONModel({
				results: [{
					complaintText: "Abladen nicht möglich - Annahmeverweigerung"
				},
				{
					complaintText: "Abladen nicht möglich - Kunde nicht angetroffen"
				},
				{
					complaintText: "Abladen nicht möglich - Sonstiges"
				},
				{
					complaintText: "Beschädigung (gesamte Sendung)"
				}]
			}), "ComplaintsModel");

                // call the base component's init function
                UIComponent.prototype.init.apply(this, arguments);

                // enable routing
                this.getRouter().initialize();

                // set the device model
                this.setModel(models.createDeviceModel(), "device");
            }
        });
    }
);